api_version = "2024-10"

[[extensions]]
uid = "44936ccc-b956-c576-fc37-de61fd1c94fc848ecf01"
type = "theme"
name = "Curetfy COD Form"
handle = "curetfy-cod-form"

  [[extensions.blocks]]
  type = "@app"
  name = "COD Buy Button"
  template = "blocks/cod-button.liquid"

  [[extensions.blocks]]
  type = "product"
  name = "COD Buy Button (Product)"
  template = "blocks/cod-button.liquid"
